    <div class="left">
      <a href="http://softmachine.dev">softmachine</a> |
      <a href="http://softmachine.dev/art">art</a> |
      <a href="http://softmachine.dev/music">music</a> |
      <a href="http://softmachine.dev/tech">tech</a> |
      <a href="http://softmachine.dev/creatures">creatures</a> |
      <a href="http://softmachine.dev/brain">brain</a> |
      <a href="http://softmachine.dev/moloch">moloch</a>
    </div>
